---
- name: Install repo package
  yum: name={{simpleca_repo_rpm}} state=present

- name: Install packages
  yum: name=globus-gsi state=present

- include: server.yml
  when: simpleca_mode == 'server'

- include: client.yml
  when: simpleca_mode == 'client'
